### ISSUE TITLE
Characters are not escaped in LaTeX, leading to render errors

### ISSUE THREAD

**Issue by prabhjotsbhatia-ca** [sinaatalay/RenderCV#129] opened 2024-07-19 06:14 UTC
**Describe the bug**
Some characters commonly used in resumes are not escaped in LaTeX, leading to render errors, or inaccurate results. 
For example, 

- "|" converts to "---"

- "$" leads to render errors (need to manually escape it with` "\" `in the YAML file) 

**To Reproduce**
Please provide a minimal YAML input as a code block for us to produce the same error.
```

    Skills:
      - >-
        Skill A | skill B | skill C
```
**Screenshots**
<img width="290" alt="image" src="https://github.com/user-attachments/assets/06df72e5-4b3a-4bb8-8066-47724144dbe1">

**Comment by sinaatalay** [comment] 2024-07-19 11:53
Thank you!

I couldn't reproduce the `"|" converts to "---"` issue. In my case, it prints "|" successfully. Could you please provide a full YAML file to reproduce?

RenderCV doesn't escape the `$` sign by default to allow users to add math. Do you think it would be better if it were escaped by default?

**Comment by prabhjotsbhatia-ca** [comment] 2024-07-23 17:56
I'm using the sb2nov theme with Latin Modern Sans Serif. You can reproduce it by just adding the pipe character "|" to any yaml element using the sb2nov theme

<img width="289" alt="image" src="https://github.com/user-attachments/assets/6311ff94-6618-4167-971a-ce98246a9342">

<img width="277" alt="image" src="https://github.com/user-attachments/assets/cd302c8c-c4bd-4a0f-980d-d5c18ae84e50">

Perhaps it is because of not using this: `\usepackage[T1]{fontenc}` as outlined here: 
https://texblog.net/latex-archive/uncategorized/symbols/

**Comment by peteza33** [comment] 2024-09-27 04:05
> Thank you!
> 
> I couldn't reproduce the `"|" converts to "---"` issue. In my case, it prints "|" successfully. Could you please provide a full YAML file to reproduce?
> 
> RenderCV doesn't escape the `$` sign by default to allow users to add math. Do you think it would be better if it were escaped by default?

FWIW I like the non-escaped $ by default (but do admit finding this issue from searching 'escaping in rendercv')

**Comment by sinaatalay** [comment] 2024-09-27 04:30
As discussed in #154, we will escape `$` but still allow users to use math with  `$$`. So if you are using math, you will be able to use it like `$$\frac{3}{4}$$`. @peteza33 You like non-escaped $ because you're using math, right?

**Comment by peteza33** [comment] 2024-10-03 04:24
yessir

**Comment by sinaatalay** [comment] 2024-11-01 23:42
This issue has been fixed. It will be released soon. Thank you!

**Closed as completed by sinaatalay** 2024-11-01 23:42 UTC
Labels: bug
