### ISSUE TITLE
Add extra line to descibe or summarise  personal contributions in each publications

### ISSUE THREAD

**Issue by dyliu0312** [sinaatalay/RenderCV#229] opened 2024-11-24 03:27 UTC
Hi, it's a very instresting and useful project which generates my CV really conveniently. 
But I'm expecting if there is any chance to add extra line in each publications to descibe or summarise personal contributions.
I think it gona be helpful for people grasping the main idea of each work more quickly.
Thank you!

**Comment by kiyose** [comment] 2024-12-03 21:08
See if #210 would address your issue.  You can see an example screenshot in the accompanying PR #211

**Comment by sinaatalay** [comment] 2024-12-25 22:33
Duplicate of #210.

**Closed as not planned by sinaatalay** 2024-12-25 22:33 UTC
Labels: enhancement
