### ISSUE TITLE
Feature Request: pronouns field in the first grouping

### ISSUE THREAD

**Issue by averagejoey2000** [sinaatalay/RenderCV#88] opened 2024-05-29 06:16 UTC
I can have a less subtle inclusion of this by putting them after my name in the name field, but it might not be optimal to have them displayed in the big heading font like the name is. It should be easily visible and you should be able to see it quickly, but not obtrusively, like you may have seen in email signatures.

**Comment by sinaatalay** [comment] 2024-05-29 12:45
Thank you for opening an issue! This would be a nice addition, but the problem is visually designing such a thing. It's the same reason I cannot implement #28 very easily: I want to ensure all the default PDF designs are on point, and the more features come, the more maintenance it requires.

Fortunately, RenderCV is flexible enough to achieve such things. I suggest you edit the `Header.j2.tex` file, which is located in your theme LaTeX source folder that comes with the `rendercv new` command ([see docs for details](https://docs.rendercv.com/user_guide/#getting-started-with-the-new-command)).

I would suggest something like ([line 7 for the classic theme](https://docs.rendercv.com/reference/themes/classic/#header)):

```latex
    \textbf{<<cv.name>>}\textsubscript{\normalsize he/him}
```

Maybe we could add this to the FAQ in the user guide.

Let me know if you have any further questions. I am closing this issue for now.

**Closed as not planned by sinaatalay** 2024-05-29 12:45 UTC
Labels: enhancement
